### ISSUE TITLE
Need documentation of all the features of `Lanceur`

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur#105]
## TODO
 - [x] Documentation of the main features
 - [x] Documentation of _Calculator_ plugin
 - [x] Documentation of _Spotify_ plugin
 - [x] Documentation of _Clipboard_ plugin
 - [x] Documentation of _Evernote_ plugin
 - [x] Documentation of data reconciliation [_Doubloons_]
 - [x] Documentation of data reconciliation [_Unsed keywords_]
