### ISSUE TITLE
Dependencies need refactoring

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur#130]
# Todo

 - [x] Review the dependency graph
 - [x] Review the nuget package
 - [x] Edit the dependency script to take into account the .Net standard `.csproj`. Below xml example

``` XML
<ItemGroup>
    <ProjectReference Include="..\..\Probel.Lanceur.Core\Probel.Lanceur.Core.csproj" />
    <ProjectReference Include="..\..\Probel.Lanceur.SharedKernel\Probel.Lanceur.SharedKernel.csproj" />
  </ItemGroup>

```

# Dependencies (how it was)
![image](https://user-images.githubusercontent.com/2678545/90977505-42d5ca00-e546-11ea-9d6f-f32cd32bb727.png)

# Dependencies (how it is)

![image](https://user-images.githubusercontent.com/2678545/90799793-0458c900-e314-11ea-895b-602a2c8a322c.png)

**Comment by jibedoubleve** [comment]
## Dependencies to remove
![image](https://user-images.githubusercontent.com/2678545/90750301-e324b800-e2d4-11ea-92c0-22046c62ac85.png)

**Comment by jibedoubleve** [comment]
## New dependency graph

![image](https://user-images.githubusercontent.com/2678545/90799549-ab893080-e313-11ea-96f1-a33ba5f4be8b.png)
