### ISSUE TITLE
Add mini calculator

### ISSUE THREAD

**Issue by jibedoubleve** [jibedoubleve/lanceur#4]
## Todo
 - [ ] Analyse the GUI
 - [ ] Do I include it as a plugin?
 - [ ] Analyse how it'll work internally
